[package]
name = "wasmtime-hello-world"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
wasmtime = "0.33.0"
anyhow = "1.0.53"
wasmtime-wasi = "0.33"